spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        registration:
          kakao:
            client_id: ${KAKAO_CLIENT_ID}
            client_secret: ${KAKAO_CLIENT_SECRET}
            client_authentication_method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization_grant_type: authorization_code
            scope:
              - profile_nickname
              - account_email

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://ec2-43-203-62-127.ap-northeast-2.compute.amazonaws.com:8080/oauth2/callback/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: naver

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://ec2-43-203-62-127.ap-northeast-2.compute.amazonaws.com:8080/oauth2/callback/google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: google
            scope:
              - email
              - profile
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

auth:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    accessTokenExpirationHour: ${JWT_ACCESS_EXPIRATION_HOUR}


