spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

auth:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    accessTokenExpirationHour: ${JWT_ACCESS_EXPIRATION_HOUR}

oauth2:
  client:
    provider:
      kakao:
        authorization_url: https://kauth.kakao.com/oauth/authorize
        token_url: https://kauth.kakao.com/oauth/token
        user_info_url: https://kapi.kakao.com/v2/user/me
        user_name_attribute: id
    registration:
      kakao:
        client_id: ${KAKAO_CLIENT_ID}
        client_secret: ${KAKAO_CLIENT_SECRET}
        client_authentication_method: client_secret_post
        redirect_url: ${KAKAO_REDIRECT_URL}
        authorization_grant_type: authorization_code

