package com.challengeteamkotlin.campdaddy.common.config

import com.challengeteamkotlin.campdaddy.infrastructure.client.properties.KakaoProviderProperties
import com.challengeteamkotlin.campdaddy.infrastructure.client.properties.KakaoRegistrationProperties
import com.challengeteamkotlin.campdaddy.infrastructure.jwt.JwtProperties
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(KakaoProviderProperties::class, KakaoRegistrationProperties::class, JwtProperties::class)
class PropertiesConfig